(require 'rest-utils)

(defconst rest-expands--expandable-property 'rest-expands--expadable)
(defconst rest-expands--collapsible-property 'rest-expands--collapsible)

(defun rest-expands-insert-expandable-text (content text-provider)
  "Insert a toggleable header (the newline is added automatically).

The inserted text can be toggled with the rest-expands--toggle-text
function: the expansion will be generated by the text-provider function.

The text provided shouldn't be terminated with a newline, unless an extra 
one is desired"
  (insert
   (rest-utils--propertize-text content
                                rest-expands--expandable-property
                                text-provider)))

(defun rest-expands--jump-to-header ()
  "Move up until a header is hit"
  (while (and (rest-expands--on-expanded-text?)
              (not (= -1 (forward-line -1))))))

(defun rest-expands--get-expanded-text ()
  (funcall
   (get-text-property (point)
                      rest-expands--expandable-property)))

(defun rest-expands--expand-text ()
  "Expand the text in the header"
  (let ((text (rest-expands--get-expanded-text)))
    (save-excursion
      (goto-char (line-end-position))
      ;;; TODO/FIXME this is bogus: wrong properties!
      (insert (concat "\n" text )))))

(defun rest-expands--collapse-text ()
  "Collapse the text at point"
  (save-excursion
    (while (and (not (= (forward-line) 1))
                (rest-expands--on-expanded-text?))
      (kill-line))))

(defun rest-expands--on-expandable-text? ()
  (get-text-property (point)
                     rest-expands--expandable-property))

(defun rest-expands--on-expanded-text? ()
  (get-text-property (point)
                     rest-expands--collapsible-property))

(defun rest-expands--next-line-expanded? ()
  (save-excursion
    (and (not (= (forward-line) 1))
         (rest-expands--on-expanded-text?))))

(defun rest-expands--on-header-of-expanded-text? ()
  (and (rest-expands--on-expandable-text?)
         (rest-expands-next-line-expanded?)))

(defun rest-expands-toggle-text ()
  (interactive)
  (cond
   ((rest-expands--on-header-of-expanded-text?)
    (rest-expands--collapse-text))
   ((rest-expands--on-expandable-text?)
    (rest-expands--expand-text))
   ((rest-expands--on-expanded-text?)
    (rest-expands--jump-to-header)
    (rest-expands--collapse-text))))

(provide 'rest-expand)
