(require 'rest-utils)
(require 'rest-state)

(defun rest-list--toggle-line ()
  (interactive)
  (let ((inhibit-read-only t))
    (rest-expand-toggle-text)))

(defun rest-list--bind-keys (refresh-action)
  (rest-open-bind-key)  
  (local-set-key (kbd "r") refresh-action)
  (local-set-key (kbd "q") 'rest-utils-close-buffer)
  (local-set-key (kbd "TAB") 'rest-list--toggle-line))

(defun rest-list-show (buffer-name content-function)
  (rest-utils-wipe-buffer-if-present buffer-name)
  (switch-to-buffer buffer-name)
  (font-lock-mode)
  (rest-utils-force-read-only)
  (rest-list--bind-keys (lambda ()
                          (interactive)
                          (rest-state-init)
                          (rest-list-show buffer-name content-function)))  
  (let ((inhibit-read-only t))
    (funcall content-function))
  (lexical-let ((buffer-name buffer-name)
                (content-function content-function))))

(provide 'rest-list)
